### ISSUE TITLE
Conglomerate point cloud into objects

### ISSUE THREAD

**Issue by andrewbriand** [huskyroboticsteam/PY2020#11]
We need to put together the angle and distance point cloud data into objects (maybe just circles to start, we can make more complex shapes later)

**Comment by matthewstarkey** [comment]
So we want the entire frame to be inputed through the algorithm to cluster objects, will this be stored as a vector I imagine?

**Comment by andrewbriand** [comment]
Yes, I think vector is the best option, we can pass frames by const reference from the LIDAR class unless you need to modify them

**Comment by Aion253** [comment]
See @matthewstarkey commit [fb5d0ae0f1281f1681812e29a5f9e091914b545d](https://github.com/huskyroboticsteam/PY2020/commit/fb5d0ae0f1281f1681812e29a5f9e091914b545d)
