### ISSUE TITLE
How do I add myself to clickup

### ISSUE THREAD

**Issue by Tadtiger13** [huskyroboticsteam/PY2020#2]
I have a clickup account, but do not know how to use it. I appear to have two different accounts already? Why not use Jira?

**Comment by spencerlu** [comment]
I would like to second this

**Comment by evan3334** [comment]
bruh :joy: :joy: :joy:

**Comment by husky-robotics** [comment]
Jira costs money and is software development + agile focused.  We found something that is free and will work well for the wider team.
